version: '3.8'

services:
  delta-sharing-server:
    image: deltaio/delta-sharing-server:0.7.8
    ports:
      - "8080:8080"
    volumes:
      - ./data:/data
      - ./config/delta-sharing-server-config.yaml:/config/delta-sharing-server-config.yaml
    command: ["--config", "/config/delta-sharing-server-config.yaml"]
