[tool.poetry]
name = "delta-sharing-example"
version = "0.1.0"
description = ""
authors = ["Andrés Wallberg <andre.wv@hotmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
